### ISSUE TITLE
Acknowledging authorship

### ISSUE THREAD

**Issue by evbogue** [sunnankar/farbeyondthestars#1]
Hey Trace,

Could I get you to put somewhere on the content of this site that it was written by me, is not maintained by me, and also wasn't published in 2015? 

Ev Bogue

**Comment by sunnankar** [comment]
@evbogue Sure. I wanted to get the full archives loaded in eventually but it just has not been very high on the todo list. Want to submit the pull requests you would like to see?

**Comment by evbogue** [comment]
Sure. It's it cool if we try to reach a consensus between what you want and what I want before I try to wrap my head around how Jekyll works? I'm more familiar with Node.js static site generators.

The gist of it is that you own and maintain Farbeyondthestars.com, and you're using the website to host the content that I wrote at Farbeyondthestars.com between October 2009 and February 2011. 

All of the content I wrote on Farbeyondthestars.com was and is in the public domain "Uncopyright", so you can do anything you want with it. But I'd love if it was clear that I don't maintain farbeyondthestars.com and you do. 

Is that how you see it or do you have other ideas?

**Comment by sunnankar** [comment]
Jekyll is pretty easy as all you would need to do is edit the .md (Markdown) files which is very similar to HTML. You should not need to tinker with any of the real Jekyll components.

Sounds fine with making it clear on the maintenance/ownership. I am not particularly picky about the domain currently because I am working on other projects.

The plan currently is to fill in the old archived content so the link structure is back in place. It still gets some traffic from referrals. Then I want to explore other content creation ideas for it since the title is great for the sci-fi type feel. I think it would be a fun outlet for some ideas I have.
